# Generated by Django 5.2.4 on 2025-07-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcash', '0001_initial'),
        ('references', '0002_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowcash',
            options={'verbose_name': 'Движение средств', 'verbose_name_plural': 'Движения средств'},
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='amount',
            field=models.FloatField(max_length=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='flowcash',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.type', verbose_name='Тип'),
        ),
    ]
